# https://gohugo.io/getting-started/configuration/

title: Durumi-AA
baseURL: https://aa.durumi.io
languageCode: ko-kr
hasCJKLanguage: true
defaultContentLanguage: ko

theme:
  - github.com/team-durumi/tailwind-aa-theme
  - github.com/team-durumi/hugo-search-fuse-js-aa

build:
  writeStats: true

taxonomies:
  tag: tags
  subject: subjects
  creator: creators
  venue: venues
  source: sources

paginate: 10