# https://gohugo.io/getting-started/configuration/

title: Durumi-AA
baseURL: https://aa.durumi.io
languageCode: ko-kr
hasCJKLanguage: true
defaultContentLanguage: ko

build:
  writeStats: true

taxonomies:
  tag: tags
  subject: subjects
  creator: creators
  venue: venues
  source: sources

paginate: 10