ko:
  languageName: Korean
  contentDir: content
  weight: 1
en:
  anguageName: English
  contentDir: content.en
  title: Durumi-AA
  description: Team Durumi Developers Group in Seoul
  weight: 2
  menu:
    main:
      - name: Home
        url: /
        weight: -120
      - name: About
        url: /about
        weight: -110
      - name: Tools
        url: /about
        weight: 1
        parent: About    
      - name: Posts
        url: /posts/
        weight: 2
        parent: About
      - name: Design-System
        url: /marketing
        weight: 3
        parent: About
      - name: Github
        url: https://github.com/team-durumi
        weight: 4
        parent: About                  
      - name: Browse
        url: /items
        weight: -100
      - name: Search
        url: /search
        weight: -90
      - name: Collections
        url: 
        weight: -80
      - name: Tags
        url: /tags/
        weight: 1
        parent: Collections     
      - name: Creators
        url: /creators/
        weight: 2
        parent: Collections     
      - name: Subjects
        url: /subjects/
        weight: 3
        parent: Collections       
      - name: Sources
        url: /sources/
        weight: 4
        parent: Collections     
      - name: Venues
        url: /venues/
        parent: Collections
        weight: 5
      - name: Exhibitions
        url: /exhibitions/
        weight: -70

    # 푸터메뉴
    footer:
      - name: About
        url: /about
        weight: -110
      - name: Tools
        url: /about
        weight: 1
        parent: About     
      - name: Posts
        url: /posts/
        weight: 2
        parent: About
      - name: Design-System
        url: /marketing
        weight: 3
        parent: About
      - name: Github
        url: https://github.com/team-durumi
        weight: 4
        parent: About
      - name: Browse
        url: 
        weight: -100                     
      - name: Browse Items
        url: /items
        weight: 1
        parent: Browse    
      - name: Search
        url: /search
        weight: 2
        parent: Browse
      - name: Search Engine Results
        url: https://catalog.ccwps.org/
        weight: 3
        parent: Browse       
      - name: Collections
        url: 
        weight: -80
      - name: Tags
        url: /tags/
        weight: 1
        parent: Collections     
      - name: Creators
        url: /creators/
        weight: 2
        parent: Collections     
      - name: Subjects
        url: /subjects/
        weight: 3
        parent: Collections       
      - name: Sources
        url: /sources/
        weight: 4
        parent: Collections     
      - name: Venues
        url: /venues/
        parent: Collections
        weight: 5
      - name: Collection-whisky
        url: /en/collection-whisky
        parent: Collections     
        weight: 6
      - name: Exhibitions
        url: /exhibitions/
        weight: -70  