title: Durumi-AA
description: Team Durumi는 시민사회영역과 IT개발 영역에서 10년 이상의 경력을 가진 구성원 중심으로 구성된 5명의 개발팀입니다.
images:
  - img/design-system-figma-preview.png

license:
  title_of_work: ROLL
  link_to_work: https://roll.durumi.io
  createor_of_work: Team-Durumi
  link_to_creator_profile: https://github.com/team-durumi
  year_of_creation: 2024

footer:
  logo: img/durumi.png
  대표전화: 02-0000-0000
  팩스: 02-0000-0000
  주소: Somewhere in Seoul
  이메일: team@durumi.io
  url: http://github.com/team-durumi
  caption: Github
  github: http://github.com/team-durumi
  fb: 
  tw: 
  instagram: 
  linkedin:

cfImagePrefix: 'https://durumi.io/cdn-cgi/image'
cfImageStyles:
  thumb: 'fit=scale-down,width=300'
  full: 'fit=scale-down,width=1920'

image_extension_whitelist:
  - jpg
  - jpeg
  - png
  - gif
  - JPG