baseURL = "https://aa.durumi.io"
languageCode = "kr-ko"
title = "Durumi-AA"
theme = ["tailwind-aa-theme", "hugo-debugprint", "hugo-search-fuse-js"]

[taxonomies]
  tag = "tags"
  creator = "creators"

paginate = "5"

[build]
# Used by PurgeCSS
writeStats = true

[permalinks]
  items = "/:section/:sections[last]/:title/"


[menu]

  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Browse"
  URL = "items"
  weight = 3

  [[menu.main]]
  name = "Search"
  URL = "search"
  weight = 4

  [[menu.main]]
  name = "Tags"
  URL = "tags"
  weight = 5

  [[menu.main]]
  name = "Creators"
  URL = "creators"
  weight = 6

  [[menu.main]]
  name = "Blog"
  URL = "posts"
  weight = 7

  [[menu.main]]
  name = "Components"
  URL = "marketing"
  weight = 8

  [[menu.main]]
  name = "Whisky Collection"
  URL = "/collection-whisky"
  weight = 9 

  [[menu.main]]
  name = "Sitemap.xml"
  URL = "sitemap.xml"
  weight = 10



  ############# footer menu #############
  [[menu.footer]]
  name = "Marketing Layout"
  URL = "marketing"
  weight = 1

  [[menu.footer]]
  name = "(C)items"
  URL = "items"
  weight = 2