baseURL = "https://aa.durumi.io"
languageCode = "kr-ko"
title = "tailwind-aa-0.1"
theme = ["tailwind-aa-theme", "hugo-debugprint", "hugo-search-fuse-js"]
disableKinds = ["taxonomy", "term"]

[build]
# Used by PurgeCSS
writeStats = true

[permalinks]
  items = "/:title/"


[menu]

  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Components"
  URL = "marketing"
  weight = 6

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Browse"
  URL = "items"
  weight = 3

  [[menu.main]]
  name = "Blog"
  URL = "posts"
  weight = 5

  [[menu.main]]
  name = "Search"
  URL = "search"
  weight = 4  

  ############# footer menu #############
  [[menu.footer]]
  name = "Marketing Layout"
  URL = "marketing"
  weight = 1

  [[menu.footer]]
  name = "(C)items"
  URL = "items"
  weight = 2