baseURL = "https://aa.durumi.io"
languageCode = "kr-ko"
title = "Durumi-AA"
theme = ["hugo-search-fuse-js-aa", "tailwind-aa-theme" ]

[taxonomies]
  tag = "tags"
  subject = "subjects"
  creator = "creators"
  venue = "venues"
  source = "sources"

paginate = "10"


[build]
# Used by PurgeCSS
writeStats = true

[permalinks]
  items = "/:sections/:title/"


[menu]

  [[menu.main]]
  name = "Browse"
  URL = "items"
  weight = 1

  [[menu.main]]
  name = "Search"
  URL = "search"
  weight = 2

  [[menu.main]]
  name = "Search(TS)"
  URL = "https://ts-ccwps.durumi.io"
  weight = 3

  [[menu.main]]
  name = "Tags"
  URL = "tags"
  weight = 4

  [[menu.main]]
  name = "Creators"
  URL = "creators"
  weight = 5  

  [[menu.main]]
  name = "Subjects"
  URL = "subjects"
  weight = 6  

  [[menu.main]]
  name = "Sources"
  URL = "sources"
  weight = 7

  [[menu.main]]
  name = "Venues"
  URL = "venues"
  weight = 8

  [[menu.main]]
  name = "Blog"
  URL = "posts"
  weight = 9

  [[menu.main]]
  name = "Components"
  URL = "marketing"
  weight = 10

  ############# footer menu #############
  [[menu.footer]]
  name = "Marketing Layout"
  URL = "marketing"
  weight = 1

  [[menu.footer]]
  name = "(C)items"
  URL = "items"
  weight = 2


