baseURL = "https://romantic-visvesvaraya-014147.netlify.app/"
languageCode = "kr-ko"
title = "tailwind-aa-tester"
theme = ["tailwind-aa-theme", "hugo-debugprint"]
disableKinds = ["taxonomy", "term"]

[build]
# Used by PurgeCSS
writeStats = true

[permalinks]
  items = "/:title/"


[menu]

  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "Marketing Layout"
  URL = "marketing"
  weight = 2

  [[menu.main]]
  name = "(C)items"
  URL = "items"
  weight = 3

  [[menu.main]]
  name = "(C)posts"
  URL = "posts"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Marketing Layout"
  URL = "marketing"
  weight = 1

  [[menu.footer]]
  name = "(C)items"
  URL = "items"
  weight = 2