baseURL = "https://aa.durumi.io"
languageCode = "kr-ko"
title = "Durumi-AA"
theme = ["hugo-search-fuse-js", "tailwind-aa-theme","hugo-debugprint" ]

[taxonomies]
  tag = "tags"
  subject = "subjects"
  creator = "creators"
  venue = "venues"
  source = "sources"

paginate = "10"


[build]
# Used by PurgeCSS
writeStats = true

[permalinks]
  items = "/:sections/:title/"


[menu]

  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Browse(content)"
  URL = "items"
  weight = 3

  [[menu.main]]
  name = "Browse(csv)"
  URL = "browse"
  weight = 4  

  [[menu.main]]
  name = "Search"
  URL = "search"
  weight = 5

  [[menu.main]]
  name = "Search(ts)"
  URL = "https://gifted-cray-fb4a47.netlify.app/"
  weight = 6 

  [[menu.main]]
  name = "Tags"
  URL = "tags"
  weight = 7

  [[menu.main]]
  name = "Creators"
  URL = "creators"
  weight = 8

  [[menu.main]]
  name = "Blog"
  URL = "posts"
  weight = 9

  [[menu.main]]
  name = "Components"
  URL = "marketing"
  weight = 10

  [[menu.main]]
  name = "Whisky Collection"
  URL = "/collection-whisky"
  weight = 11 

  [[menu.main]]
  name = "Sitemap.xml"
  URL = "sitemap.xml"
  weight = 12



  ############# footer menu #############
  [[menu.footer]]
  name = "Marketing Layout"
  URL = "marketing"
  weight = 1

  [[menu.footer]]
  name = "(C)items"
  URL = "items"
  weight = 2


