baseURL = "https://sad-ptolemy-43f516.netlify.app"
languageCode = "kr-ko"
title = "tailwind-aa-tester"
theme = "starter"
disableKinds = ["taxonomy", "term"]

[build]
# Used by PurgeCSS
writeStats = true
