baseURL = "https://romantic-visvesvaraya-014147.netlify.app/"
languageCode = "kr-ko"
title = "tailwind-aa-tester"
theme = "tailwind-aa-theme"
disableKinds = ["taxonomy", "term"]

[build]
# Used by PurgeCSS
writeStats = true

[permalinks]
  items = "/:title/"